{
  #'variables' : {'ippijg' : 0},
  'conditions': [
    ['OS=="linux"', {
      'target_defaults': {
        'cflags': ['-fPIC', '-g', '-O3', '-pthread'],
        'defines': ['OS_LINUX'],
      },
    },],
    ['OS=="win"', {
      'target_defaults': {
        'defines': ['OS_WIN', 'WIN32', 'MSWINDOWS', 'NOMINMAX', 'UNICODE', '_UNICODE', 'WIN32_LEAN_AND_MEAN', '_WIN32_WINNT=0x0501'],
        'msvs_settings': {
          'VCLinkerTool': {'GenerateDebugInformation': 'true',},
          'VCCLCompilerTool': {'DebugInformationFormat': '3',},
        },
      },
    },],
  ],
  'targets': [
    {
      'target_name': 'magick',
      'type': 'static_library',
      'msvs_guid': '530A3D4E-84AE-4B06-9581-ADFBDE3FEF29',
      'cflags': ['-fopenmp'],
      'defines': ['HAVE_OPENMP'],
      'dependencies': [],
      'conditions':[
        ['OS=="win"', {
          'include_dirs': ['port'],
          'sources': [
            'port/magick/magick_config.h',
            '../src/3rdparty/GraphicsMagick-stable/magick/nt_base.c',
            '../src/3rdparty/GraphicsMagick-stable/magick/nt_base.h',
            '../src/3rdparty/GraphicsMagick-stable/magick/nt_feature.c',
            '../src/3rdparty/GraphicsMagick-stable/magick/nt_feature.h',
          ],
          'direct_dependent_settings': {
            'include_dirs': ['port'],
          },
        }],
        ['OS=="linux"', {
          'include_dirs': ['port_linux', ],
          'sources': [
            'port_linux/magick/magick_config.h',
          ],
          'direct_dependent_settings': {
            'include_dirs': ['port_linux'],
            'libraries': ['-lgomp'],
          },
        }],
      ],
      'include_dirs': [
        '../src/3rdparty/zlib-stable',
        '../src/3rdparty/GraphicsMagick-stable',
      ],
      'direct_dependent_settings': {
          'include_dirs': ['../src/3rdparty/GraphicsMagick-stable'],
      },
      'sources': [
'../src/3rdparty/GraphicsMagick-stable/magick/analyze.c',
'../src/3rdparty/GraphicsMagick-stable/magick/animate.c',
'../src/3rdparty/GraphicsMagick-stable/magick/annotate.c',
'../src/3rdparty/GraphicsMagick-stable/magick/attribute.c',
'../src/3rdparty/GraphicsMagick-stable/magick/average.c',
'../src/3rdparty/GraphicsMagick-stable/magick/bit_stream.c',
'../src/3rdparty/GraphicsMagick-stable/magick/blob.c',
'../src/3rdparty/GraphicsMagick-stable/magick/cdl.c',
'../src/3rdparty/GraphicsMagick-stable/magick/channel.c',
'../src/3rdparty/GraphicsMagick-stable/magick/color.c',
'../src/3rdparty/GraphicsMagick-stable/magick/color_lookup.c',
'../src/3rdparty/GraphicsMagick-stable/magick/colormap.c',
'../src/3rdparty/GraphicsMagick-stable/magick/colorspace.c',
'../src/3rdparty/GraphicsMagick-stable/magick/command.c',
'../src/3rdparty/GraphicsMagick-stable/magick/compare.c',
'../src/3rdparty/GraphicsMagick-stable/magick/composite.c',
'../src/3rdparty/GraphicsMagick-stable/magick/compress.c',
'../src/3rdparty/GraphicsMagick-stable/magick/confirm_access.c',
'../src/3rdparty/GraphicsMagick-stable/magick/constitute.c',
'../src/3rdparty/GraphicsMagick-stable/magick/decorate.c',
'../src/3rdparty/GraphicsMagick-stable/magick/delegate.c',
'../src/3rdparty/GraphicsMagick-stable/magick/deprecate.c',
'../src/3rdparty/GraphicsMagick-stable/magick/describe.c',
'../src/3rdparty/GraphicsMagick-stable/magick/display.c',
'../src/3rdparty/GraphicsMagick-stable/magick/draw.c',
'../src/3rdparty/GraphicsMagick-stable/magick/effect.c',
'../src/3rdparty/GraphicsMagick-stable/magick/enhance.c',
'../src/3rdparty/GraphicsMagick-stable/magick/enum_strings.c',
'../src/3rdparty/GraphicsMagick-stable/magick/error.c',
'../src/3rdparty/GraphicsMagick-stable/magick/fx.c',
'../src/3rdparty/GraphicsMagick-stable/magick/gem.c',
'../src/3rdparty/GraphicsMagick-stable/magick/gradient.c',
'../src/3rdparty/GraphicsMagick-stable/magick/hclut.c',
'../src/3rdparty/GraphicsMagick-stable/magick/image.c',
'../src/3rdparty/GraphicsMagick-stable/magick/list.c',
'../src/3rdparty/GraphicsMagick-stable/magick/locale.c',
'../src/3rdparty/GraphicsMagick-stable/magick/log.c',
'../src/3rdparty/GraphicsMagick-stable/magick/magic.c',
'../src/3rdparty/GraphicsMagick-stable/magick/magick.c',
'../src/3rdparty/GraphicsMagick-stable/magick/magick_endian.c',
'../src/3rdparty/GraphicsMagick-stable/magick/map.c',
'../src/3rdparty/GraphicsMagick-stable/magick/memory.c',
'../src/3rdparty/GraphicsMagick-stable/magick/module.c',
'../src/3rdparty/GraphicsMagick-stable/magick/monitor.c',
'../src/3rdparty/GraphicsMagick-stable/magick/montage.c',
#'../src/3rdparty/GraphicsMagick-stable/magick/nt_base.c',
#'../src/3rdparty/GraphicsMagick-stable/magick/nt_feature.c',
'../src/3rdparty/GraphicsMagick-stable/magick/omp_data_view.c',
'../src/3rdparty/GraphicsMagick-stable/magick/operator.c',
'../src/3rdparty/GraphicsMagick-stable/magick/paint.c',
'../src/3rdparty/GraphicsMagick-stable/magick/pixel_cache.c',
'../src/3rdparty/GraphicsMagick-stable/magick/pixel_iterator.c',
'../src/3rdparty/GraphicsMagick-stable/magick/plasma.c',
'../src/3rdparty/GraphicsMagick-stable/magick/PreRvIcccm.c',
'../src/3rdparty/GraphicsMagick-stable/magick/profile.c',
'../src/3rdparty/GraphicsMagick-stable/magick/quantize.c',
'../src/3rdparty/GraphicsMagick-stable/magick/random.c',
'../src/3rdparty/GraphicsMagick-stable/magick/registry.c',
'../src/3rdparty/GraphicsMagick-stable/magick/render.c',
'../src/3rdparty/GraphicsMagick-stable/magick/resize.c',
'../src/3rdparty/GraphicsMagick-stable/magick/resource.c',
'../src/3rdparty/GraphicsMagick-stable/magick/segment.c',
'../src/3rdparty/GraphicsMagick-stable/magick/semaphore.c',
'../src/3rdparty/GraphicsMagick-stable/magick/shear.c',
'../src/3rdparty/GraphicsMagick-stable/magick/signature.c',
#'../src/3rdparty/GraphicsMagick-stable/magick/static.c',
'graphmagick_static.c',
'../src/3rdparty/GraphicsMagick-stable/magick/statistics.c',
'../src/3rdparty/GraphicsMagick-stable/magick/tempfile.c',
'../src/3rdparty/GraphicsMagick-stable/magick/texture.c',
'../src/3rdparty/GraphicsMagick-stable/magick/timer.c',
'../src/3rdparty/GraphicsMagick-stable/magick/transform.c',
'../src/3rdparty/GraphicsMagick-stable/magick/tsd.c',
'../src/3rdparty/GraphicsMagick-stable/magick/type.c',
'../src/3rdparty/GraphicsMagick-stable/magick/unix_port.c',
'../src/3rdparty/GraphicsMagick-stable/magick/utility.c',
'../src/3rdparty/GraphicsMagick-stable/magick/version.c',
'../src/3rdparty/GraphicsMagick-stable/magick/widget.c',
# '../src/3rdparty/GraphicsMagick-stable/magick/xwindow.c',
'../src/3rdparty/GraphicsMagick-stable/magick/alpha_composite.h',
'../src/3rdparty/GraphicsMagick-stable/magick/analyze.h',
'../src/3rdparty/GraphicsMagick-stable/magick/animate.h',
'../src/3rdparty/GraphicsMagick-stable/magick/api.h',
'../src/3rdparty/GraphicsMagick-stable/magick/attribute.h',
'../src/3rdparty/GraphicsMagick-stable/magick/average.h',
'../src/3rdparty/GraphicsMagick-stable/magick/bit_stream.h',
'../src/3rdparty/GraphicsMagick-stable/magick/blob.h',
'../src/3rdparty/GraphicsMagick-stable/magick/cdl.h',
'../src/3rdparty/GraphicsMagick-stable/magick/channel.h',
'../src/3rdparty/GraphicsMagick-stable/magick/color.h',
'../src/3rdparty/GraphicsMagick-stable/magick/color_lookup.h',
'../src/3rdparty/GraphicsMagick-stable/magick/colormap.h',
'../src/3rdparty/GraphicsMagick-stable/magick/colorspace.h',
'../src/3rdparty/GraphicsMagick-stable/magick/command.h',
'../src/3rdparty/GraphicsMagick-stable/magick/common.h',
'../src/3rdparty/GraphicsMagick-stable/magick/compare.h',
'../src/3rdparty/GraphicsMagick-stable/magick/composite.h',
'../src/3rdparty/GraphicsMagick-stable/magick/compress.h',
'../src/3rdparty/GraphicsMagick-stable/magick/confirm_access.h',
'../src/3rdparty/GraphicsMagick-stable/magick/constitute.h',
'../src/3rdparty/GraphicsMagick-stable/magick/decorate.h',
'../src/3rdparty/GraphicsMagick-stable/magick/delegate.h',
'../src/3rdparty/GraphicsMagick-stable/magick/deprecate.h',
'../src/3rdparty/GraphicsMagick-stable/magick/describe.h',
'../src/3rdparty/GraphicsMagick-stable/magick/display.h',
'../src/3rdparty/GraphicsMagick-stable/magick/draw.h',
'../src/3rdparty/GraphicsMagick-stable/magick/effect.h',
'../src/3rdparty/GraphicsMagick-stable/magick/enhance.h',
'../src/3rdparty/GraphicsMagick-stable/magick/enum_strings.h',
'../src/3rdparty/GraphicsMagick-stable/magick/error.h',
'../src/3rdparty/GraphicsMagick-stable/magick/forward.h',
'../src/3rdparty/GraphicsMagick-stable/magick/fx.h',
'../src/3rdparty/GraphicsMagick-stable/magick/gem.h',
'../src/3rdparty/GraphicsMagick-stable/magick/gradient.h',
'../src/3rdparty/GraphicsMagick-stable/magick/hclut.h',
'../src/3rdparty/GraphicsMagick-stable/magick/image.h',
'../src/3rdparty/GraphicsMagick-stable/magick/list.h',
'../src/3rdparty/GraphicsMagick-stable/magick/locale_c.h',
'../src/3rdparty/GraphicsMagick-stable/magick/log.h',
'../src/3rdparty/GraphicsMagick-stable/magick/magic.h',
'../src/3rdparty/GraphicsMagick-stable/magick/magick_config_api.h',
#'../src/3rdparty/GraphicsMagick-stable/magick/magick_config.h',
'../src/3rdparty/GraphicsMagick-stable/magick/magick_endian.h',
'../src/3rdparty/GraphicsMagick-stable/magick/magick.h',
'../src/3rdparty/GraphicsMagick-stable/magick/magick_types.h',
'../src/3rdparty/GraphicsMagick-stable/magick/map.h',
'../src/3rdparty/GraphicsMagick-stable/magick/memory.h',
'../src/3rdparty/GraphicsMagick-stable/magick/module.h',
'../src/3rdparty/GraphicsMagick-stable/magick/monitor.h',
'../src/3rdparty/GraphicsMagick-stable/magick/montage.h',
'../src/3rdparty/GraphicsMagick-stable/magick/nt_base.h',
'../src/3rdparty/GraphicsMagick-stable/magick/nt_feature.h',
'../src/3rdparty/GraphicsMagick-stable/magick/omp_data_view.h',
'../src/3rdparty/GraphicsMagick-stable/magick/operator.h',
'../src/3rdparty/GraphicsMagick-stable/magick/paint.h',
'../src/3rdparty/GraphicsMagick-stable/magick/pixel_cache.h',
'../src/3rdparty/GraphicsMagick-stable/magick/pixel_iterator.h',
'../src/3rdparty/GraphicsMagick-stable/magick/plasma.h',
'../src/3rdparty/GraphicsMagick-stable/magick/PreRvIcccm.h',
'../src/3rdparty/GraphicsMagick-stable/magick/profile.h',
'../src/3rdparty/GraphicsMagick-stable/magick/quantize.h',
'../src/3rdparty/GraphicsMagick-stable/magick/random.h',
'../src/3rdparty/GraphicsMagick-stable/magick/registry.h',
'../src/3rdparty/GraphicsMagick-stable/magick/render.h',
'../src/3rdparty/GraphicsMagick-stable/magick/resize.h',
'../src/3rdparty/GraphicsMagick-stable/magick/resource.h',
'../src/3rdparty/GraphicsMagick-stable/magick/semaphore.h',
'../src/3rdparty/GraphicsMagick-stable/magick/shear.h',
'../src/3rdparty/GraphicsMagick-stable/magick/signature.h',
'../src/3rdparty/GraphicsMagick-stable/magick/spinlock.h',
'../src/3rdparty/GraphicsMagick-stable/magick/static.h',
'../src/3rdparty/GraphicsMagick-stable/magick/statistics.h',
'../src/3rdparty/GraphicsMagick-stable/magick/studio.h',
'../src/3rdparty/GraphicsMagick-stable/magick/symbols.h',
'../src/3rdparty/GraphicsMagick-stable/magick/tempfile.h',
'../src/3rdparty/GraphicsMagick-stable/magick/texture.h',
'../src/3rdparty/GraphicsMagick-stable/magick/timer.h',
'../src/3rdparty/GraphicsMagick-stable/magick/transform.h',
'../src/3rdparty/GraphicsMagick-stable/magick/tsd.h',
'../src/3rdparty/GraphicsMagick-stable/magick/type.h',
'../src/3rdparty/GraphicsMagick-stable/magick/unix_port.h',
'../src/3rdparty/GraphicsMagick-stable/magick/utility.h',
'../src/3rdparty/GraphicsMagick-stable/magick/version.h',
'../src/3rdparty/GraphicsMagick-stable/magick/widget.h',
'../src/3rdparty/GraphicsMagick-stable/magick/xwindow.h',
      ],
    },
    {
      'target_name': 'magickpp',
      'type': 'static_library',
      'msvs_guid': '863AA8BC-DAEA-4BC5-BA62-3B57F68B55AE',
      'defines': [],
      'dependencies': [
        'magick',
      ],
      'include_dirs': [
		'../src/3rdparty/GraphicsMagick-stable/Magick++/lib',
      ],
      'conditions':[],
      'sources': [
'../src/3rdparty/README.txt',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Blob.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/BlobRef.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/CoderInfo.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Color.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Drawable.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Exception.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Functions.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Geometry.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Image.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/ImageRef.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Montage.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Options.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Pixels.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/STL.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Thread.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/TypeMetric.cpp',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/Blob.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/BlobRef.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/CoderInfo.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/Color.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/Drawable.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/Exception.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/Functions.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/Geometry.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/Image.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/ImageRef.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/Include.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/Montage.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/Options.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/Pixels.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/STL.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/Thread.h',
'../src/3rdparty/GraphicsMagick-stable/Magick++/lib/Magick++/TypeMetric.h',
      ],
      'direct_dependent_settings': {
        'include_dirs': ['../src/3rdparty/GraphicsMagick-stable/Magick++/lib'],
      },
      'export_dependent_settings': [
          'magick',
      ],
    },
    {
      'target_name': 'coders',
      'type': 'static_library',
      'msvs_guid': 'A5CC0608-3FB8-44B0-9F81-48049848D0E4',
      'dependencies': [
        #'libjpeg.gyp:libjpeg',
        'libpng.gyp:libpng',
        'magick',
      ],
      'export_dependent_settings': [
          'magick',
      ],
      'include_dirs': [
        '../src/3rdparty/libpng-stable',
        '../src/3rdparty/zlib-stable',
      ],
      'conditions':[
        ['ippijg==1', {
          'dependencies': ['ippijg.gyp:ippijg',],
        },],
        ['ippijg==0', {
          'dependencies': ['libjpeg.gyp:libjpeg',],
        },],
      ],
      'sources': [
'../src/3rdparty/GraphicsMagick-stable/coders/jpeg.c',
'../src/3rdparty/GraphicsMagick-stable/coders/png.c',
'../src/3rdparty/GraphicsMagick-stable/coders/bmp.c',
'../src/3rdparty/GraphicsMagick-stable/coders/pnm.c',
'../src/3rdparty/GraphicsMagick-stable/coders/gif.c',
# '../src/3rdparty/GraphicsMagick-stable/coders/tiff.c',
      ],
    },
  ],
}
