{
  'conditions': [
    ['OS=="linux"', {
      'target_defaults': {
        'cflags': ['-fPIC', '-g', '-O3',],
        #'defines': ['OS_LINUX'],
      },
    },],
    ['OS=="win"', {
      'target_defaults': {
        'msvs_settings': {
          'VCLinkerTool': {'GenerateDebugInformation': 'true',},
          'VCCLCompilerTool': {'DebugInformationFormat': '3',},
        },
      },
    },],
  ],
  'targets': [
  {
    'target_name': 'ippijg',
    'type': 'static_library',
    'msvs_guid': '762EE335-5C3B-48CB-98B6-6160FD21FEF4',
    'include_dirs': [
      '../src/3rdparty/ippijg/include',
      '../src/3rdparty/ippijg/_include',
    ],
    'defines': ['linux',],
    'sources':['../src/3rdparty/ippijg/include/jconfig.h',
'../src/3rdparty/ippijg/include/jerror.h',
'../src/3rdparty/ippijg/_include/jinclude.h',
'../src/3rdparty/ippijg/_include/jmemsys.h',
'../src/3rdparty/ippijg/include/jmorecfg.h',
'../src/3rdparty/ippijg/_include/jpegint.h',
'../src/3rdparty/ippijg/_include/jpegipp.h',
'../src/3rdparty/ippijg/include/jpeglib.h',
'../src/3rdparty/ippijg/include/jversion.h',
'../src/3rdparty/ippijg/_src/jcapimin.c',
'../src/3rdparty/ippijg/_src/jcmarker.c',
'../src/3rdparty/ippijg/_src/jdapimin.c',
'../src/3rdparty/ippijg/_src/jdinput.c',
'../src/3rdparty/ippijg/_src/jdtrans.c',
'../src/3rdparty/ippijg/_src/jidctred.c',
'../src/3rdparty/ippijg/_src/jcapistd.c',
'../src/3rdparty/ippijg/_src/jcmaster.c',
'../src/3rdparty/ippijg/_src/jdapistd.c',
'../src/3rdparty/ippijg/_src/jdmainct.c',
'../src/3rdparty/ippijg/_src/jerror.c',
'../src/3rdparty/ippijg/_src/jmemmgr.c',
'../src/3rdparty/ippijg/_src/jccoefct.c',
'../src/3rdparty/ippijg/_src/jcomapi.c',
'../src/3rdparty/ippijg/_src/jdatadst.c',
'../src/3rdparty/ippijg/_src/jdmarker.c',
'../src/3rdparty/ippijg/_src/jfdctflt.c',
'../src/3rdparty/ippijg/_src/jmemnobs.c',
'../src/3rdparty/ippijg/_src/jccolor.c',
'../src/3rdparty/ippijg/_src/jcparam.c',
'../src/3rdparty/ippijg/_src/jdatasrc.c',
'../src/3rdparty/ippijg/_src/jdmaster.c',
'../src/3rdparty/ippijg/_src/jfdctfst.c',
'../src/3rdparty/ippijg/_src/jquant1.c',
'../src/3rdparty/ippijg/_src/jcdctmgr.c',
'../src/3rdparty/ippijg/_src/jcphuff.c',
'../src/3rdparty/ippijg/_src/jdcoefct.c',
'../src/3rdparty/ippijg/_src/jdmerge.c',
'../src/3rdparty/ippijg/_src/jfdctint.c',
'../src/3rdparty/ippijg/_src/jquant2.c',
'../src/3rdparty/ippijg/_src/jchuff.c',
'../src/3rdparty/ippijg/_src/jcprepct.c',
'../src/3rdparty/ippijg/_src/jdcolor.c',
'../src/3rdparty/ippijg/_src/jdphuff.c',
'../src/3rdparty/ippijg/_src/jidctflt.c',
'../src/3rdparty/ippijg/_src/jutils.c',
'../src/3rdparty/ippijg/_src/jcinit.c',
'../src/3rdparty/ippijg/_src/jcsample.c',
'../src/3rdparty/ippijg/_src/jddctmgr.c',
'../src/3rdparty/ippijg/_src/jdpostct.c',
'../src/3rdparty/ippijg/_src/jidctfst.c',
'../src/3rdparty/ippijg/_src/jcmainct.c',
'../src/3rdparty/ippijg/_src/jctrans.c',
'../src/3rdparty/ippijg/_src/jdhuff.c',
'../src/3rdparty/ippijg/_src/jdsample.c',
'../src/3rdparty/ippijg/_src/jidctint.c',
    ],
    'direct_dependent_settings': {
      'include_dirs': ['../src/3rdparty/ippijg/include'],
    },
  },
  ],
}
