{
  'conditions': [
    ['OS=="linux"', {
      'target_defaults': {
        'cflags': ['-fPIC', '-g', '-O3',],
        #'defines': ['OS_LINUX'],
      },
    },],
    ['OS=="win"', {
      'target_defaults': {
        # 'cflags': ['-fPIC', '-g', '-O2',],
        #'defines': ['OS_WIN', 'WIN32', 'NOMINMAX', 'UNICODE', '_UNICODE', 'WIN32_LEAN_AND_MEAN', '_WIN32_WINNT=0x0501'],
        'msvs_settings': {
          'VCLinkerTool': {'GenerateDebugInformation': 'true',},
          'VCCLCompilerTool': {'DebugInformationFormat': '3',},
        },
      },
    },],
  ],
  'targets': [
  {
    'target_name': 'libjpeg',
    'type': 'static_library',
    'msvs_guid': '762EE334-4C3B-48CB-98B6-5050FD21FEF4',
    'include_dirs': ['../src/3rdparty/jpeg-stable'],
    'defines': ['TEMP_DIRECTORY="/tmp/"'],
    'sources':[
# '../src/3rdparty/jpeg-stable/ansi2knr.c',
# '../src/3rdparty/jpeg-stable/cdjpeg.c',
# '../src/3rdparty/jpeg-stable/cjpeg.c',
# '../src/3rdparty/jpeg-stable/ckconfig.c',
#'../src/3rdparty/jpeg-stable/djpeg.c',
#'../src/3rdparty/jpeg-stable/example.c',
'../src/3rdparty/jpeg-stable/jaricom.c',
'../src/3rdparty/jpeg-stable/jcapimin.c',
'../src/3rdparty/jpeg-stable/jcapistd.c',
'../src/3rdparty/jpeg-stable/jcarith.c',
'../src/3rdparty/jpeg-stable/jccoefct.c',
'../src/3rdparty/jpeg-stable/jccolor.c',
'../src/3rdparty/jpeg-stable/jcdctmgr.c',
'../src/3rdparty/jpeg-stable/jchuff.c',
'../src/3rdparty/jpeg-stable/jcinit.c',
'../src/3rdparty/jpeg-stable/jcmainct.c',
'../src/3rdparty/jpeg-stable/jcmarker.c',
'../src/3rdparty/jpeg-stable/jcmaster.c',
'../src/3rdparty/jpeg-stable/jcomapi.c',
'../src/3rdparty/jpeg-stable/jcparam.c',
'../src/3rdparty/jpeg-stable/jcprepct.c',
'../src/3rdparty/jpeg-stable/jcsample.c',
'../src/3rdparty/jpeg-stable/jctrans.c',
'../src/3rdparty/jpeg-stable/jdapimin.c',
'../src/3rdparty/jpeg-stable/jdapistd.c',
'../src/3rdparty/jpeg-stable/jdarith.c',
'../src/3rdparty/jpeg-stable/jdatadst.c',
'../src/3rdparty/jpeg-stable/jdatasrc.c',
'../src/3rdparty/jpeg-stable/jdcoefct.c',
'../src/3rdparty/jpeg-stable/jdcolor.c',
'../src/3rdparty/jpeg-stable/jddctmgr.c',
'../src/3rdparty/jpeg-stable/jdhuff.c',
'../src/3rdparty/jpeg-stable/jdinput.c',
'../src/3rdparty/jpeg-stable/jdmainct.c',
'../src/3rdparty/jpeg-stable/jdmarker.c',
'../src/3rdparty/jpeg-stable/jdmaster.c',
'../src/3rdparty/jpeg-stable/jdmerge.c',
'../src/3rdparty/jpeg-stable/jdpostct.c',
'../src/3rdparty/jpeg-stable/jdsample.c',
'../src/3rdparty/jpeg-stable/jdtrans.c',
'../src/3rdparty/jpeg-stable/jerror.c',
'../src/3rdparty/jpeg-stable/jfdctflt.c',
'../src/3rdparty/jpeg-stable/jfdctfst.c',
'../src/3rdparty/jpeg-stable/jfdctint.c',
'../src/3rdparty/jpeg-stable/jidctflt.c',
'../src/3rdparty/jpeg-stable/jidctfst.c',
'../src/3rdparty/jpeg-stable/jidctint.c',
'../src/3rdparty/jpeg-stable/jmemansi.c',
# '../src/3rdparty/jpeg-stable/jmemdos.c',
# '../src/3rdparty/jpeg-stable/jmemmac.c',
'../src/3rdparty/jpeg-stable/jmemmgr.c',
'../src/3rdparty/jpeg-stable/jmemname.c',
# '../src/3rdparty/jpeg-stable/jmemnobs.c',
# '../src/3rdparty/jpeg-stable/jpegtran.c',
'../src/3rdparty/jpeg-stable/jquant1.c',
'../src/3rdparty/jpeg-stable/jquant2.c',
'../src/3rdparty/jpeg-stable/jutils.c',
'../src/3rdparty/jpeg-stable/rdbmp.c',
'../src/3rdparty/jpeg-stable/rdcolmap.c',
'../src/3rdparty/jpeg-stable/rdgif.c',
# '../src/3rdparty/jpeg-stable/rdjpgcom.c',
'../src/3rdparty/jpeg-stable/rdppm.c',
'../src/3rdparty/jpeg-stable/rdrle.c',
'../src/3rdparty/jpeg-stable/rdswitch.c',
'../src/3rdparty/jpeg-stable/rdtarga.c',
'../src/3rdparty/jpeg-stable/transupp.c',
'../src/3rdparty/jpeg-stable/wrbmp.c',
'../src/3rdparty/jpeg-stable/wrgif.c',
# '../src/3rdparty/jpeg-stable/wrjpgcom.c',
'../src/3rdparty/jpeg-stable/wrppm.c',
'../src/3rdparty/jpeg-stable/wrrle.c',
'../src/3rdparty/jpeg-stable/wrtarga.c',
    ],
    'direct_dependent_settings': {
      'include_dirs': ['../src/3rdparty/jpeg-stable'],
    },
  },
  ],
}
