{{! test template}}
Hallo, das ist ein Täst
GLOBAL_FOO {{GLOBAL_FOO}}
GLOBAL_INT {{GLOBAL_INT}}
GLOBAL_LONG {{GLOBAL_LONG}}

METHOD_FOO {{METHOD_FOO}}
METHOD_INT {{METHOD_INT}}
METHOD_LONG {{METHOD_LONG}}

DICT_FOO {{DICT_FOO}}
DICT_INT {{DICT_INT}}
DICT_LONG {{DICT_LONG}}
DICT_TUPLE {{DICT_TUPLE}}

ESCAPE_HTML {{ESCAPE_HTML:html_escape}}
ESCAPE_JS {{ESCAPE_JS:javascript_escape}}
